### ISSUE TITLE
Support for UNIX_FD

### ISSUE THREAD

**Issue by directhex** [mono/dbus-sharp#57]
The DBus spec defines a UNIX_FD type, short code `h`, as "Unsigned 32-bit integer representing an index into an out-of-band array of file descriptors, transferred via some platform-specific mechanism (mnemonic: h for handle)"

This type is missing from DBus#, and is needed for MonoDevelop.

**Comment by brookpatten** [comment]
I haven't looked at it in a while, but I implemented rough receive-only support in a fork https://github.com/brookpatten/dbus-sharp shortly after the relevant bits were added to mono.posix for socket control messages.  I don't know if this is useful to your or not, but if so I could clean it up and PR it.  I remember there was a lot of overlap between dbus-sharp socket implementations and the updated mono.posix sockets that would probably remove a lot of dbus-sharp code.

That being said, unix sockets are not my wheelhouse and somebody with more knowledge could probably do it better.

**Comment by directhex** [comment]
Hm. @garuma?

**Comment by garuma** [comment]
@brookpatten yeah that seems like an excellent start, if you can PR the relevant parts I will review it.

/cc @directhex

**Comment by brookpatten** [comment]
Sure that will give me a good excuse to clean it up.

**Comment by brookpatten** [comment]
@garuma one of the things that is needed to use the socket control messages in mono.posix is to change the target framework to 4.6+.  I'm sure this has a lot of consequences, but at the same time 3.5 is definitely quite old at this point.  Are you OK with changing the target framework?

**Comment by directhex** [comment]
@brookpatten IMHO there's no pressing reason not to bump that up, but maybe add a configure.ac check for a recent-enough Mono to provide that?

**Comment by directhex** [comment]
@brookpatten  OK, I'm trying to test this, but... I'm having trouble with sending an FD?

The relevant part of /org/freedesktop/Flatpak/Development HostCommand method is `a{uh}`, i.e. a dictionary of `unit` and `unix_fd`. I'm using the following to try & populate that:

```
Dictionary<uint, FileDescriptor> fds = new Dictionary<uint, FileDescriptor> ();
fds.Add (Mono.Unix.UnixStream.StandardOutputFileDescriptor, new FileDescriptor (Mono.Unix.UnixStream.StandardOutputFileDescriptor));
fds.Add (Mono.Unix.UnixStream.StandardInputFileDescriptor, new FileDescriptor (Mono.Unix.UnixStream.StandardInputFileDescriptor));
fds.Add (Mono.Unix.UnixStream.StandardErrorFileDescriptor, new FileDescriptor (Mono.Unix.UnixStream.StandardErrorFileDescriptor));
```

But at actual runtime, it fails:

```
System.NullReferenceException: Object reference not set to an instance of an object
  at DBus.Protocol.MessageWriter.Write (DBus.FileDescriptor fd) [0x00002] in /run/build/dbus-sharp/src/Protocol/MessageWriter.cs:229 
  at (wrapper dynamic-method) DBus.Protocol.MessageWriter:WriteFileDescriptor (DBus.Protocol.MessageWriter,DBus.FileDescriptor)
  at DBus.Protocol.MessageWriter.WriteFromDict[TKey,TValue] (System.Collections.Generic.IDictionary`2[TKey,TValue] val) [0x00069] in /run/build/dbus-sharp/src/Protocol/MessageWriter.cs:482 
```

Which seems to be implying the FileDescriptor objects are no good?

What am I doing wrong here?

**Comment by brookpatten** [comment]
Sorry, you're not doing anything wrong, I've just only implemented receiving them, not sending.
I believe it should be straightforward given what's in place, I just haven't had the time.

**Comment by directhex** [comment]
Okay, good to have it confirmed, means I'm not going mad. I'll shelve current MD work, and return to it at a later date

**Comment by directhex** [comment]
What magnitude of bribe will it cost me for you to find time sooner rather than later?

**Comment by garuma** [comment]
We can at least start the process of merging this initial read support I'd say, @brookpatten would you mind creating a PR for your branch?

By the way I'm ok with the 4.6 shift too.
